- name: RPM Key
  rpm_key:
    key: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Has Repo
  shell:
    cmd: zypper repos | grep packages-microsoft-com-prod | cat
    warn: false
  register: repo
  changed_when: False

- name: Repo Present
  community.general.zypper_repository:
    repo: 'https://packages.microsoft.com/config/opensuse/15/prod.repo'
    state: present
  when: not repo.stdout

- name: Installed
  package:
    name: dotnet-sdk-3.1
    state: present
