- name: Installed
  become: yes
  package:
    name: firefox
    state: present

- name: Create Profile
  shell: firefox -CreateProfile default-release -headless
  become: yes
  become_user: nathan

- name: Get Profile Folder
  shell: find ~/.mozilla/firefox "$(pwd -P)" -maxdepth 1 -name '*.default-release'
  register: profile
  changed_when: False
  become: yes
  become_user: nathan

- name: Update User Preferences
  copy:
    src: user.js
    dest: "{{ profile.stdout }}/user.js"

- name: Update Preferences
  copy:
    src: prefs.js
    dest: "{{ profile.stdout }}/prefs.js"

- name: Update Profiles
  copy:
    src: profiles.ini
    dest: ~/.mozilla/firefox/profiles.ini
  become: yes
  become_user: nathan

- name: Set Profiles
  ini_file:
    path: ~/.mozilla/firefox/profiles.ini
    section: Profile0
    option: Path
    value: "{{ profile.stdout | basename }}"
    no_extra_spaces: yes
  become: yes
  become_user: nathan

- name: Set Profiles
  ini_file:
    path: ~/.mozilla/firefox/profiles.ini
    section: Install11457493C5A56847
    option: Default
    value: "{{ profile.stdout | basename }}"
    no_extra_spaces: yes
  become: yes
  become_user: nathan
