- name: Installed
  become: yes
  package:
    name: firefox
    state: present

- name: Create Profile
  shell: firefox -CreateProfile default-release -headless
  become: yes
  become_user: nathan

- name: Get Profile Folder
  shell: find ~/.mozilla/firefox "$(pwd -P)" -maxdepth 1 -name '*.default-release'
  register: profile
  changed_when: False
  become: yes
  become_user: nathan

- name: Update Preferences
  copy:
    src: user.js
    dest: "{{ profile.stdout }}/user.js"
