- name: Installed
  package:
    name: firefox
    state: present

- name: Get Existing Profile
  shell: find ~/.mozilla/firefox "$(pwd -P)" -maxdepth 1 -name '*.default-release' | cat
  register: existingprofile
  changed_when: False
  become: yes
  become_user: nathan

- name: Create Profile
  shell: firefox -CreateProfile default-release -headless
  become: yes
  become_user: nathan
  when: not existingprofile.stdout

- name: Get Profile Folder
  shell: find ~/.mozilla/firefox "$(pwd -P)" -maxdepth 1 -name '*.default-release'
  register: profile
  changed_when: False
  become: yes
  become_user: nathan

- name: Set Profiles
  ini_file:
    path: ~/.mozilla/firefox/profiles.ini
    section: Profile0
    option: Path
    value: "{{ profile.stdout | basename }}"
    no_extra_spaces: yes
  become: yes
  become_user: nathan

- name: Set Profiles
  ini_file:
    path: ~/.mozilla/firefox/profiles.ini
    section: Install11457493C5A56847
    option: Default
    value: "{{ profile.stdout | basename }}"
    no_extra_spaces: yes
  become: yes
  become_user: nathan
