- name: Installed
  become: yes
  package:
    name: chromium
    state: present

- name: Desktop Name
  become: yes
  ini_file:
    path: /usr/share/applications/chromium-browser.desktop
    section: Desktop Entry
    option: Name
    value: Chromium
