- name: Projects Directory Exists
  file:
    path: ~/Projects
    state: directory
  become: yes
  become_user: nathan

- name: Downloads Directory Exists
  file:
    path: ~/Downloads
    state: directory
  become: yes
  become_user: nathan

- name: Templates Directory Does Not Exist
  file:
    path: ~/Templates
    state: absent
  become: yes
  become_user: nathan

- name: Bin Directory Does Not Exist
  file:
    path: ~/bin
    state: absent
  become: yes
  become_user: nathan

- name: Snap Directory Does Not Exist
  file:
    path: ~/snap
    state: absent
  become: yes
  become_user: nathan

- name: Public Directory Does Not Exist
  file:
    path: ~/Public
    state: absent
  become: yes
  become_user: nathan
