- name: Include Tasks
  include: run.yml
  when: ansible_virtualization_type == 'virtualbox'

- name: Warn
  fail:
    msg: Role '{{ role_name }}' is not supported when using virtualization '{{ ansible_virtualization_type }}'
  ignore_errors: yes
  when: ansible_virtualization_type != 'virtualbox'
