- name: DNS Over TLS - Copy Configuration File
  copy:
    src: resolved.conf
    dest: /etc/systemd/resolved.conf

- name: DNS Over TLS - Copy Network Manager File
  copy:
    src: 10-dns-systemd-resolved.conf
    dest: /etc/NetworkManager/conf.d/10-dns-systemd-resolved.conf

- name: DNS Over TLS - Start & Enable Systemd Resolved
  systemd:
    name: systemd-resolved
    state: started
    enabled: yes

- name: DNS Over TLS - Reload Network Manager
  systemd:
    name: NetworkManager
    state: reloaded
  changed_when: False
