- name: Include RedHat Tasks
  include: rhel.yml
  when: ansible_os_family == 'RedHat'

- name: Include Suse Tasks
  include: suse.yml
  when: ansible_os_family == 'Suse'

- name: Installed
  become: yes
  package:
    name: code
    state: present

- name: Desktop Name
  become: yes
  ini_file:
    path: /usr/share/applications/code.desktop
    section: Desktop Entry
    option: Name
    value: VS Code

- name: Config Directory Exists
  file:
    path: ~/.config/Code/User
    state: directory

- name: Settings File Sync
  copy:
    src: settings.json
    dest: ~/.config/Code/User/settings.json

- name: Keybindings File Sync
  copy:
    src: keybindings.json
    dest: ~/.config/Code/User/keybindings.json
