- name: Fedora
  include: fedora.yml
  when: ansible_distribution == 'Fedora'

- name: openSUSE
  include: opensuse.yml
  when: ansible_distribution in ['openSUSE Tumbleweed', 'openSUSE Leap']

- name: Installed
  package:
    name: code
    state: present

- name: Desktop Name
  ini_file:
    path: /usr/share/applications/code.desktop
    section: Desktop Entry
    option: Name
    value: VS Code

- name: Config Directory Exists
  file:
    path: ~/.config/Code/User
    state: directory
  become: yes
  become_user: nathan

- name: Settings File Sync
  copy:
    src: settings.json
    dest: ~/.config/Code/User/settings.json
  become: yes
  become_user: nathan

- name: Keybindings File Sync
  copy:
    src: keybindings.json
    dest: ~/.config/Code/User/keybindings.json
  become: yes
  become_user: nathan
