- name: Fedora
  include: fedora.yml
  when: ansible_distribution == 'Fedora'

- name: openSUSE
  include: opensuse.yml
  when: ansible_distribution in ['openSUSE Tumbleweed', 'openSUSE Leap']

- name: Installed
  package:
    name: code
    state: present

- name: Desktop Name
  ini_file:
    path: /usr/share/applications/code.desktop
    section: Desktop Entry
    option: Name
    value: VS Code
