- name: Linux
  include_tasks: linux.yml
  when: ansible_distribution in ['Fedora', 'openSUSE Tumbleweed', 'openSUSE Leap']

- name: Warning (Distribution)
  debug:
    msg: Role '{{ role_name }}' is not supported on OS family '{{ ansible_distribution }}'
  when: ansible_distribution not in ['Fedora', 'openSUSE Tumbleweed', 'openSUSE Leap']
