- name: Sanity Check
  fail:
    msg: Role '{{ role_name }}' is not supported on OS family '{{ ansible_os_family }}'
  when: ansible_os_family not in ['RedHat', 'Suse']

- name: Include RedHat Tasks
  include: rhel.yml
  when: ansible_os_family == 'RedHat'

- name: Include RedHat Tasks
  include: suse.yml
  when: ansible_os_family == 'Suse'

- name: VS Code - Installed
  become: yes
  package:
    name: code
    state: present

- name: VS Code - Config Directory Exists
  file:
    path: ~/.config/Code/User
    state: directory

- name: VS Code - Settings File Sync
  copy:
    src: settings.json
    dest: ~/.config/Code/User/settings.json

- name: VS Code - Keybindings File Sync
  copy:
    src: keybindings.json
    dest: ~/.config/Code/User/keybindings.json

- name: VS Code - Desktop Name
  become: yes
  ini_file:
    path: /usr/share/applications/code.desktop
    section: Desktop Entry
    option: Name
    value: VS Code
