- name: Yum Key & Repo
  become: yes
  yum_repository:
    name: vscode
    description: VS Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    gpgcheck: yes
