- name: openSUSE
  include_tasks: opensuse.yml
  when: ansible_distribution in ['openSUSE Tumbleweed', 'openSUSE Leap']

- name: Uninstalled
  become: yes
  package:
    name:
    - opensuse-welcome
    - tigervnc
    - xterm
    - ksysguard5
    - khelpcenter5
    - git-gui
    - appimagelauncher
    state: absent
