- name: Sanity Check
  fail:
    msg: Role '{{ role_name }}' is not supported on OS family '{{ ansible_os_family }}'
  when: ansible_os_family not in ['RedHat', 'Debian', 'Suse', 'Gentoo', 'Archlinux', 'Alpine']

- name: Uninstalled
  become: yes
  package:
    name:
    - opensuse-welcome
    - tigervnc
    - xterm
    - ksysguard5
    - khelpcenter5
    - git-gui
    state: absent
