- name: openSUSE
  include_tasks: opensuse.yml
  when: ansible_distribution in ['openSUSE Tumbleweed', 'openSUSE Leap']

- name: Unix
  include_tasks: unix.yml
  when: ansible_distribution != 'Windows'

- name: Linux
  include_tasks: linux.yml
  when: ansible_kernel_family == 'Linux'

- name: Warning (Distribution)
  debug:
    msg: Role '{{ role_name }}' is not supported on distribution '{{ ansible_distribution }}'
  when: ansible_distribution == 'Windows'

- name: Warning (Kernel)
  debug:
    msg: Role '{{ role_name }}' is not supported on kernel '{{ ansible_kernel_family }}'
  when: ansible_kernel_family != 'Linux'
