- name: Has Local Repositories
  shell:
    cmd: zypper repos --show-enabled-only --uri | grep cd | cat
    warn: false
  register: localrepos
  changed_when: False

- name: No Local Repositories
  shell:
    cmd: zypper removerepo --local
    warn: false
  when: localrepos.stdout

- name: No Downloaded Packages
  shell:
    cmd: zypper clean
    warn: false

- name: No Old Kernels
  shell:
    cmd: zypper purge-kernels
    warn: false

- name: No Old Journal Logs
  shell:
    cmd: journalctl --vacuum-time=1d

- name: Patterns Uninstalled
  community.general.zypper:
    name:
      - patterns-games-games
      - patterns-kde-kde_games
      - patterns-kde-kde_pim
    type: pattern
    state: removed
