- name: Has Local Repositories
  become: yes
  shell:
    cmd: zypper repos --show-enabled-only | grep --count cd
    warn: false
  register: localrepos
  changed_when: False

- name: No Local Repositories
  become: yes
  shell:
    cmd: zypper removerepo --local
    warn: false
  when: localrepos.stdout != "0"
