- name: KWin File Sync
  copy:
    src: kwinrc
    dest: ~/.config/kwinrc
  become: yes
  become_user: nathan

- name: Applets File Sync
  copy:
    src: appletsrc
    dest: ~/.config/plasma-org.kde.plasma.desktop-appletsrc
  become: yes
  become_user: nathan

- name: Globals File Sync
  copy:
    src: kdeglobals
    dest: ~/.config/kdeglobals
  become: yes
  become_user: nathan

- name: Splash File Sync
  copy:
    src: ksplashrc
    dest: ~/.config/ksplashrc
  become: yes
  become_user: nathan

- name: Server File Sync
  copy:
    src: ksmserverrc
    dest: ~/.config/ksmserverrc
  become: yes
  become_user: nathan

- name: Plasma File Sync
  copy:
    src: plasmarc
    dest: ~/.config/plasmarc
  become: yes
  become_user: nathan
