- name: Installed
  package:
    name: mbpfan

- name: Service File Exists
  copy:
    src: mbpfan.service
    dest: /etc/systemd/system/mbpfan.service

- name: Service Enabled
  systemd:
    name: mbpfan.service
    enabled: yes
  register: enabled

- name: Systemd Config Reloaded
  systemd:
    daemon_reload: yes
  when: enabled.changed

- name: Start Service
  systemd:
    name: mbpfan.service
    state: started

- name: Get Minimum Speed
  shell:
    chdir: /sys/devices/platform/applesmc.768
    cmd: echo $(($(cat fan*_min | sort -n | head -1) + 500))
  register: speedmin
  changed_when: False

- name: Get Maximum Speed
  shell:
    chdir: /sys/devices/platform/applesmc.768
    cmd: cat fan*_max | sort -n | tail -1
  register: speedmax
  changed_when: False

- name: Get Maximum Temperature
  shell: echo $(($(cat /sys/devices/platform/coretemp.*/hwmon/hwmon*/temp*_max | sort -n | tail -1) / 1000))
  register: tempmax
  changed_when: False

- name: Set Minimum Speed
  lineinfile:
    path: /etc/mbpfan.conf
    regexp: 'min_fan1_speed = '
    line: 'min_fan1_speed = {{ speedmin.stdout }}'

- name: Set Maximum Speed
  lineinfile:
    path: /etc/mbpfan.conf
    regexp: 'max_fan1_speed = '
    line: 'max_fan1_speed = {{ speedmax.stdout }}'

- name: Set Maximum Temperature
  lineinfile:
    path: /etc/mbpfan.conf
    regexp: 'max_temp = '
    line: 'max_temp = {{ tempmax.stdout }}'

- name: Set Polling Interval
  lineinfile:
    path: /etc/mbpfan.conf
    regexp: 'polling_interval = '
    line: 'polling_interval = 2'
