- name: Tilde Remapped To D
  lineinfile:
    path: /usr/share/X11/xkb/keycodes/evdev
    regexp: '<TLDE> = '
    line: '        <TLDE> = 40;'

- name: D Remapped To Tilde
  lineinfile:
    path: /usr/share/X11/xkb/keycodes/evdev
    regexp: '<AC03> = '
    line: '        <AC03> = 49;'
