- name: GPE06 File Exists
  copy:
    src: disable-gpe06.service
    dest: /etc/systemd/system/disable-gpe06.service

- name: GPE17 File Exists
  copy:
    src: disable-gpe17.service
    dest: /etc/systemd/system/disable-gpe17.service

- name: SCI File Exists
  copy:
    src: disable-sci.service
    dest: /etc/systemd/system/disable-sci.service

- name: SCI_NOT File Exists
  copy:
    src: disable-sci.service
    dest: /etc/systemd/system/disable-sci_not.service

- name: GPE06 Service Started
  systemd:
    name: disable-gpe06.service
    state: started
    enabled: yes

- name: GPE17 Service Started
  systemd:
    name: disable-gpe17.service
    state: started
    enabled: yes

- name: SCI Service Started
  systemd:
    name: disable-sci.service
    state: started
    enabled: yes

- name: SCI_NOT Service Started
  systemd:
    name: disable-sci_not.service
    state: started
    enabled: yes
