- name: openSUSE Tumbleweed
  include_tasks: opensuse-tumbleweed.yml
  when: ansible_distribution == 'openSUSE Tumbleweed'

- name: Linux
  include_tasks: linux.yml
  when: ansible_kernel_family == 'Linux'

- name: Warning (Distribution)
  debug:
    msg: Role '{{ role_name }}' is not supported on distribution '{{ ansible_distribution }}'
  when: ansible_distribution != 'openSUSE Tumbleweed'

- name: Warning (Kernel)
  debug:
    msg: Role '{{ role_name }}' is not supported on kernel '{{ ansible_kernel_family }}'
  when: ansible_kernel_family != 'Linux'
