- name: openSUSE Tumbleweed
  become: true
  community.general.zypper:
    name: '*'
    state: dist-upgrade
  when: ansible_distribution == 'openSUSE Tumbleweed'

- name: Warning (Distribution)
  debug:
    msg: Role '{{ role_name }}' is not supported on distribution '{{ ansible_distribution }}'
  when: ansible_distribution != 'openSUSE Tumbleweed'
