- name: openSUSE Tumbleweed
  include_tasks: opensuse-tumbleweed.yml
  when: ansible_distribution == 'openSUSE Tumbleweed'

- name: Warning (Distribution)
  debug:
    msg: Role '{{ role_name }}' is not supported on distribution '{{ ansible_distribution }}'
  when: ansible_distribution != 'openSUSE Tumbleweed'
