- name: Wallpapers Directory Not Exists
  become: yes
  file:
    path: /usr/share/wallpapers
    state: absent

- name: Backgrounds Directory Exists
  become: yes
  file:
    path: /usr/share/backgrounds
    state: directory

- name: Image Sync
  become: yes
  copy:
    src: background.png
    dest: /usr/share/backgrounds/background.png

- name: Properties Directory Exists
  become: yes
  file:
    path: /usr/share/gnome-background-properties
    state: directory

- name: Property Sync
  become: yes
  copy:
    src: backgrounds.xml
    dest: /usr/share/gnome-background-properties/backgrounds.xml

- name: Set Gnome
  dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "'file:///usr/share/backgrounds/background.png'"
