- name: Installed
  become: yes
  package:
    name: nautilus
    state: present

- name: Sort Folders First
  dconf:
    key: /org/gtk/settings/file-chooser/sort-directories-first
    value: "true"

- name: Use Standard Zoom Level
  dconf:
    key: /org/gnome/nautilus/icon-view/default-zoom-level
    value: "'standard'"
