- name: Sanity Check
  fail:
    msg: Role '{{ role_name }}' is not supported on OS family '{{ ansible_os_family }}'
  when: ansible_os_family not in ['RedHat', 'Debian', 'Suse', 'Gentoo', 'Archlinux', 'Alpine']

- name: Installed
  become: yes
  flatpak:
    name: org.audacityteam.Audacity
    remote: flathub
    state: present
  when: ansible_os_family == 'RedHat'

- name: Installed
  become: yes
  package:
    name: audacity
    state: present
  when: ansible_os_family == 'Suse'
