// -----------------------------------------------------------------------------
// All custom configuration for Firefox should go in here, not prefs.js.
// https://github.com/amq/firefox-debloat
// -----------------------------------------------------------------------------

user_pref("app.shield.optoutstudies.enabled", false);
user_pref("browser.contentblocking.category", "custom");
user_pref("browser.ctrlTab.recentlyUsedOrder", false);
user_pref("browser.discovery.enabled", false);
user_pref("browser.newtabpage.activity-stream.feeds.section.highlights", false);
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories", false);
user_pref("browser.newtabpage.activity-stream.feeds.snippets", false);
user_pref("browser.newtabpage.activity-stream.feeds.snippets", false);
user_pref("browser.newtabpage.activity-stream.showSearch", false);
user_pref("browser.newtabpage.activity-stream.topSitesRows", 2);
user_pref("browser.newtabpage.pinned", "[]");
user_pref("browser.pocket.enabled", false);
user_pref("browser.search.region", "GB");
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.startup.homepage", "about:home");
user_pref("browser.tabs.drawInTitlebar", true);
user_pref("browser.tabs.warnOnClose", false);
user_pref("datareporting.healthreport.service.enabled", false);
user_pref("datareporting.healthreport.uploadEnabled", false);
user_pref("distribution.openSUSE.bookmarksProcessed", true);
user_pref("dom.security.https_only_mode", true);
user_pref("dom.security.https_only_mode_ever_enabled", true);
user_pref("gfx.webrender.all", true);
user_pref("loop.enabled", false);
user_pref("media.autoplay.default", 5);
user_pref("media.peerconnection.ice.default_address_only", true);
user_pref("mozilla.widget.use-argb-visuals", true);
user_pref("network.cookie.cookieBehavior", 1);
user_pref("permissions.default.desktop-notification", 2);
user_pref("permissions.default.xr", 2);
user_pref("privacy.donottrackheader.enabled", true);
user_pref("privacy.trackingprotection.enabled", true);
user_pref("privacy.trackingprotection.socialtracking.enabled", true);
user_pref("signon.autofillForms", false);
user_pref("signon.generation.enabled", false);
user_pref("signon.rememberSignons", false);
user_pref("toolkit.telemetry.unified", false);
user_pref("toolkit.telemetry.enabled", false);
