- name: Installed
  package:
    name: powertop

- name: Service File Exists
  copy:
    src: powertop.service
    dest: /etc/systemd/system/powertop.service

- name: Service Enabled
  systemd:
    name: powertop.service
    enabled: yes
  register: enabled

- name: Systemd Config Reloaded
  systemd:
    daemon_reload: yes
  when: enabled.changed

- name: Service Started
  systemd:
    name: powertop.service
    state: started
