- name: Fedora
  include_tasks: fedora.yml
  when: ansible_distribution == 'Fedora'

- name: Warning (Distribution)
  debug:
    msg: Role '{{ role_name }}' is not supported on distribution '{{ ansible_distribution }}'
  when: ansible_distribution != 'Fedora'
