- name: Editor Exists
  stat:
    path: /opt/unityeditor/2019.4.18f1/
  register: editor
  changed_when: False

- name: Editor Installed
  shell:
    cmd: xvfb-run /opt/unityhub/unityhub.appimage --headless install --version 2019.4.18f1
  when: not editor.stat.exists
  become: yes
  become_user: nathan
