- name: Editor Exists
  stat:
    path: /opt/unityeditor/2019.4.18f1/
  register: editor
  changed_when: False

- name: Editor Installed
  shell:
    cmd: /opt/unityhub/unityhub.appimage --headless help install-path --set /opt/unityeditor/
  when: not editor.stat.exists
