- name: Directory Exists
  file:
    path: /opt/unityhub
    state: directory

- name: Hub Exists
  stat:
    path: /opt/unityhub/unityhub.appimage
  register: hub
  changed_when: False

- name: Hub Downloaded
  get_url:
    url: https://public-cdn.cloud.unity3d.com/hub/prod/UnityHub.AppImage
    dest: /opt/unityhub/unityhub.appimage
  when: not hub.stat.exists

- name: Hub Execute Permission
  file:
    path: /opt/unityhub/unityhub.appimage
    state: file
    mode: a+x
