- name: Directory Exists
  file:
    path: ~/.local/bin
    state: directory

- name: Hub Exists
  stat:
    path: ~/.local/bin/UnityHub.AppImage
  register: hub

- name: Hub Downloaded
  get_url:
    url: https://public-cdn.cloud.unity3d.com/hub/prod/UnityHub.AppImage
    dest: ~/.local/bin/UnityHub.AppImage
  when: not hub.exists

- name: Hub Execute Permission
  file:
    path: ~/.local/bin/UnityHub.AppImage
    state: file
    mode: a+x
