- name: Directory Exists
  file:
    path: ~/.local/bin
    state: directory

- name: Download Hub
  get_url:
    url: https://public-cdn.cloud.unity3d.com/hub/prod/UnityHub.AppImage
    dest: ~/.local/bin/UnityHub.AppImage

- name: Hub Execute Permission
  file:
    path: ~/.local/bin/UnityHub.AppImage
    state: file
    mode: a+x
